# Generated by Django 5.1 on 2024-08-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChronoCrewApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='members',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team_pics/'),
        ),
        migrations.AddField(
            model_name='members',
            name='role',
            field=models.CharField(choices=[('DEV', 'Developer'), ('TECH-LEAD', 'Technology Lead'), ('LEADER', 'IT Manager/Leader'), ('PM', 'Project Manager'), ('ANALYST', 'System Engineer'), ('PRODUCT-MANAGER', 'Product Manager'), ('TPM', 'Technical Program Manager'), ('SCRUM-MASTER', 'Scrum Master'), ('DS', 'Data Scientist'), ('QA', 'Quality Assurance'), ('UX', 'UX/UI Designer')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
