# Generated by Django 5.1 on 2024-08-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChronoCrewApi', '0002_members_bio_members_date_joined_members_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='twitter_url',
            new_name='twitter_x_url',
        ),
        migrations.AddField(
            model_name='members',
            name='core_pod_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='core_skill',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='portfolio_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
